### ISSUE TITLE
Build timing out

### ISSUE THREAD

**Issue by jurf** [paulcarroty/flathub-chart#2]
It looks like the last successful build was on September 1st: https://travis-ci.org/github/paulcarroty/flathub-app-stats/builds.

Cheers for making this, this statistics nerd greatly appreciates it. :slightly_smiling_face:

**Comment by paulcarroty** [comment]
Fixed by https://github.com/paulcarroty/flathub-app-stats/commit/8a80543cdb1a5b157ef06fb2826ee98aa7464580
